url: "https://www.canvas.schuylines.net" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "canvas" # the name of your site, e.g. ACME Corp.
logo: "/assets/images/canvas6.png"

author: Schuy H
alias: Sky # author's alias -- appears in body of mailto: link
email: schuy+canvas@schuylines.net # used in **publically available** mailto: link

sass:
  style: compressed